/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3015d
 */

import com.mathworks.engine.*;
import org.scilab.forge.jlatexmath.TeXConstants;
import org.scilab.forge.jlatexmath.TeXFormula;
import javax.swing.Icon;
public class CalculadoraFourierUI extends javax.swing.JFrame {
    private MatlabEngine eng;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraFourierUI.class.getName());

    /**
     * Creates new form CalculadoraFourierUI
     */
    public CalculadoraFourierUI() {
        initComponents();
        this.setTitle("Práctica 01 - Procesamiento Digital de Señales");
        this.setLocationRelativeTo(null);
        try {
            txtAreaResultados.setText("Iniciando motor de MATLAB... Por favor espera.");
            eng = MatlabEngine.startMatlab();
            txtAreaResultados.setText("¡MATLAB conectado correctamente!\nListo para calcular.");
        } catch (Exception e) {
            txtAreaResultados.setText("Error al iniciar MATLAB. Verifica tu instalación.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSugerencias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLimiteA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLimiteB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spnArmonicos = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();
        lblEcuacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Calculadora de Serie Trigonométrica de Fourier");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel2.setText("Sugerencias:");

        cmbSugerencias.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        cmbSugerencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personalizada...", "t", "t^2", "abs(t)", "sign(t)" }));
        cmbSugerencias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbSugerencias.addActionListener(this::cmbSugerenciasActionPerformed);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel3.setText("f(t)=");

        txtFuncion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel4.setText("Límite inferior (a):");

        txtLimiteA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel5.setText("Límite superior (b):");

        txtLimiteB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel6.setText("Número armónicos(N):");

        spnArmonicos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnArmonicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spnArmonicos.addChangeListener(this::spnArmonicosStateChanged);

        btnCalcular.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(51, 51, 51));
        btnCalcular.setText("Calcular y Graficar:");
        btnCalcular.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 102, 255)));
        btnCalcular.setOpaque(true);
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        txtAreaResultados.setEditable(false);
        txtAreaResultados.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaResultados.setColumns(20);
        txtAreaResultados.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtAreaResultados.setRows(5);
        txtAreaResultados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txtAreaResultados);

        lblEcuacion.setBackground(new java.awt.Color(255, 255, 255));
        lblEcuacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblEcuacion.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(cmbSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnArmonicos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLimiteB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLimiteA, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCalcular)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblEcuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3)
                        .addComponent(lblEcuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLimiteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLimiteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spnArmonicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        btnCalcular.setEnabled(false);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new Thread(() -> {
        try {
            // Recolectar datos
            String funcion = txtFuncion.getText();
            // Los límites los pasamos como String para que MATLAB pueda leer "-pi" o "pi"
            String limiteA = txtLimiteA.getText(); 
            String limiteB = txtLimiteB.getText();
            int n = (int) spnArmonicos.getValue();

            if(funcion.isEmpty() || limiteA.isEmpty() || limiteB.isEmpty()){
                txtAreaResultados.setText("Por favor, llena todos los campos.");
                return;
            }

            txtAreaResultados.setText("Calculando serie de Fourier en MATLAB...\n");

            // Llamar a la función de MATLAB
            // Obtener la ruta exacta del proyecto de NetBeans automáticamente
            String rutaProyecto = System.getProperty("user.dir");

            // Decirle a MATLAB que agregue esa carpeta a su radar de búsqueda
            eng.eval("addpath('" + rutaProyecto + "')");

            // Esperamos 5 variables de regreso (a0, an, bn, serie y w0)
            Object[] resultados = eng.feval(5, "calcularFourier", funcion, limiteA, limiteB, n);

            // Extraer los resultados (MATLAB los devuelve como Strings gracias a .m)
            String a0_tex = String.valueOf(resultados[0]);
            String an_tex = String.valueOf(resultados[1]);
            String bn_tex = String.valueOf(resultados[2]);
            String w0_tex = String.valueOf(resultados[3]);
            String serie_plano = String.valueOf(resultados[4]);

            // Mostrar todo en el área de texto
            javax.swing.SwingUtilities.invokeLater(() -> {
            txtAreaResultados.setText("--- RESULTADOS ANALÍTICOS ---\n\n");
            txtAreaResultados.setText("--- SERIE DE FOURIER DESARROLLADA (N=" + n + ") ---\n\n");
            txtAreaResultados.append("S(t) = " + serie_plano + "\n\n");
            //Código LaTex
            String textoLatex = "\\begin{array}{l} " +
                        "a_0 = " + a0_tex + " \\\\ " +
                        "a_n = " + an_tex + " \\\\ " +
                        "b_n = " + bn_tex + " \\\\ " +
                        "S(t) = \\frac{1}{2} \\left(" + a0_tex + "\\right) + \\sum_{n=1}^{" + n + "} \\left[ \\left(" + an_tex + "\\right) \\cos(n \\cdot " + w0_tex + " \\cdot t) + \\left(" + bn_tex + "\\right) \\sin(n \\cdot " + w0_tex + " \\cdot t) \\right]" +
                        "\\end{array}";

            TeXFormula formula = new TeXFormula(textoLatex);
    
            Icon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 16); //El número es el tamaño de letra
            lblEcuacion.setIcon(icon);
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnCalcular.setEnabled(true);
        });
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.SwingUtilities.invokeLater(() -> {
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnCalcular.setEnabled(true);
            txtAreaResultados.setText("Ocurrió un error matemático o de conexión.\n");
            txtAreaResultados.append("Asegúrate de que tus límites y función tengan sintaxis de MATLAB (ej. t^2, pi).");
        });
        }
        }).start();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSugerenciasActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) cmbSugerencias.getSelectedItem();
        // Ignoramos si eligen la opción por defecto
        if (seleccion.equals("Personalizada...")) {
            return; 
        }
        // Llenamos los campos según la elección
        if (seleccion.equals("t")) {
            txtFuncion.setText("t");
            txtLimiteA.setText("-pi");
            txtLimiteB.setText("pi");
        } else if (seleccion.equals("t^2")) {
            txtFuncion.setText("t^2");
            txtLimiteA.setText("-pi");
            txtLimiteB.setText("pi");
        } else if (seleccion.equals("abs(t)")) {
            txtFuncion.setText("abs(t)");
            txtLimiteA.setText("-1");
            txtLimiteB.setText("1");
        } else if (seleccion.equals("sign(t)")) {
            txtFuncion.setText("sign(t)");
            txtLimiteA.setText("-pi");
            txtLimiteB.setText("pi");
        }
    }//GEN-LAST:event_cmbSugerenciasActionPerformed

    private void spnArmonicosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnArmonicosStateChanged
        // TODO add your handling code here:
        // Verificar que ya haya una función escrita
        if (!txtFuncion.getText().isEmpty()) {
            // Simular un clic en el botón Calcular
            btnCalcular.doClick(); 
        }
    }//GEN-LAST:event_spnArmonicosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CalculadoraFourierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraFourierUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbSugerencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEcuacion;
    private javax.swing.JSpinner spnArmonicos;
    private javax.swing.JTextArea txtAreaResultados;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtLimiteA;
    private javax.swing.JTextField txtLimiteB;
    // End of variables declaration//GEN-END:variables
}
